---
title: "Project 3 Neural Network"
author: "Michael"
date: "March 18, 2018"
output: html_document
---



Data Preparation
```{r}
library(randomForest)
library(neuralnet)
library(nnet)

df <- read.csv('SIFT_train.csv', header=FALSE)
labels <- read.csv('label_train.csv')
df$label <- as.factor(labels$label) #add a column called label to df
df$V1 <- NULL
```

Scale Data
```{r}
scl <- function(x){(x-min(x))/(max(x)-min(x))}
target.i <- which(colnames(df)=='label')
df[,-target.i] <- data.frame(lapply(df[,-target.i], scl))
```

Dummy code Outcome Variable
Create 3 variables that pertains the labels are that being predicted
```{r}
df$l1 <- ifelse(df$label=="1", 1,0)
df$l2 <- ifelse(df$label=="2", 1,0)
df$l3 <- ifelse(df$label=="3", 1,0)
df$label <- NULL
```

Split into training and test 
```{r}
set.seed(031818)
test.i <- sample(1:nrow(df), .3*nrow(df), replace=FALSE)
test.data <- df[test.i,]
train.data <- df[-test.i,]
test.target <- labels[test.i, 'label']
```

Set up formula
```{r}
n <- names(train.data)
f <- as.formula(paste("l1 + l2 + l3 ~",paste(n[!n %in% c("l1","l2","l3")], collapse="+")))
```
Problem:Curse of Dimensionality

Gridsearch
Allows to train on all combinations of tuning parameters
```{r}
nn.tune <- expand.grid(hidden=seq(0,100, by=10),
                       act.fct=c("logistic", "tanh"))
nn.tune$accuracy <- numeric(nrow(nn.tune))

for(i in 1:nrow(nn.tune)){
nn <- neuralnet(f,
                data=train.data,
                hidden=nn.tune$hidden[i],
                act.fct=nn.tune$act.fct[i],
                linear.output=FALSE,
                lifesign="minimal")
pr.nn <- compute(nn, test.data[,4:ncol(test.data)])
nn.pred <- apply(pr.nn$net.result, 1, which.max)
nn.tune$accuracy[i] <- mean(nn.pred==test.target)
}
```

Prediction
```{r}
nn <- neuralnet(f,
                data=train.data,
                hidden=10,
                act.fct="logistic",
                linear.output=FALSE,
                lifesign="minimal")
pr.nn <- compute(nn, test.data[,4:ncol(test.data)])
nn.pred <- apply(pr.nn$net.result, 1, which.max)
mean(nn.pred==test.target)
```

