---
title: "XG Boost"
author: "Group 6"
date: "March 19, 2018"
output: html_document
---


Data Preparation
```{r}
library(xgboost)
df <- read.csv('SIFT_train.csv', header=FALSE)
labels <- read.csv('label_train.csv')
df$label <- as.factor(labels$label)
df$V1 <- NULL
```

Relabel factors for XGBoost specific num_classes requirement
```{r}
levels(df$label)[levels(df$label)=="1"] <- "0"
levels(df$label)[levels(df$label)=="2"] <- "1"
levels(df$label)[levels(df$label)=="3"] <- "2"
```

XGBoost Algorithm
```{r}
set.seed(031918)
test.i <- sample(1:nrow(df), .3*nrow(df), replace=FALSE)
test.data <- df[test.i,]
train.data <- df[-test.i,]

target.i <- which(colnames(df) == 'label')
train.data <- df[-test.i, -target.i]
train.target <- df[-test.i, target.i]


model <- xgboost(data = as.matrix(train.data), label = train.target,
                 nrounds = 2, objective = "multi:softmax", num_class = 4)

xgb.preds <- predict(model, as.matrix(test.data[,-target.i]))
mean(xgb.preds == as.numeric(test.data$label))
```