---
title: "draft_LBP"
author: "Shan He"
date: "March 17, 2018"
output: html_document
---

```{r}
packages.used=c("caret","gbm", "e1071", "DMwR", "nnet", "randomForest","OpenImageR","DT", "caTools", "EBImage", "mxnet", "pbapply", "ggthemes")
# check packages that need to be installed.
packages.needed=setdiff(packages.used,
intersect(installed.packages()[,1],
packages.used))
# install additional packages
if(length(packages.needed)>0){
install.packages(packages.needed, dependencies = TRUE)
}

library(caret)
library(gbm)
library(e1071)
library(DMwR)
library(randomForest)
library(nnet)
library(OpenImageR)
library(DT)
library(caTools)
#library(EBImage)
#library(mxnet)
library(pbapply)
library(ggthemes)

source("../lib/train.R")
source("../lib/test.R")
source("../lib/data_split.R")
```


### 1. Retrieve and split the training and test data from the dataset.

```{r}
datasplit_LBP <- data_split("lbp")

train_LBP <- datasplit_LBP$df_train

test_LBP <- datasplit_LBP$df_test
```


### 2. Classifying with various methods 

#### 2.1.1 GBM training

```{r}
baseline_LBP <- train_gbm(train_LBP)
save(baseline_LBP,file="../output/baseline_LBP.RData")
```


#### 2.1.2 GBM testing 

```{r}
load("../output/baseline_LBP.RData")
baseline_LBP.time <- baseline_LBP$time
baseline_LBP.time

baseline.test.result_LBP <- test_gbm(baseline_LBP, test_LBP)
baseline.test.accuracy_LBP <- mean(baseline.test.result_LBP == test_LBP[,1])
baseline.test.accuracy_LBP
```


#### 2.2.1 SVM training

```{r}
SVM_LBP <- train_svm(train_LBP)
save(SVM_LBP,file="../output/SVM_LBP.RData")
```


#### 2.2.2 SVM testing

```{r}
load("../output/SVM_LBP.RData")
SVM_LBP.time <- SVM_LBP$time
SVM_LBP.time

SVM.test.result_LBP <- test(SVM_LBP, test_LBP)
SVM.test.accuracy_LBP <- mean(SVM.test.result_LBP == test_LBP[,1])
SVM.test.accuracy_LBP
```


#### 2.3.1 Random Forest training

```{r}
RF_LBP <- train_rf(train_LBP)
save(RF_LBP,file="../output/RF_LBP.RData")
```


#### 2.3.2 Random Forest testing

```{r}
load("../output/RF_LBP.RData")
RF_LBP.time <- RF_LBP$time
RF_LBP.time

RF.test.result_LBP <- test(RF_LBP, test_LBP)
RF.test.accuracy_LBP <- mean(RF.test.result_LBP == test_LBP[,1])
RF.test.accuracy_LBP
```


#### 2.4.1 Logistic Regression training

```{r}
LR_LBP <- train_lr(train_LBP)
save(LR_LBP,file="../output/LR_LBP.RData")
```


#### 2.4.2 Logistic Regression testing

```{r}
load("../output/LR_LBP.RData")
LR_LBP.time <- LR_LBP$time
LR_LBP.time

LR.test.result_LBP <- test(LR_LBP, test_LBP)
LR.test.accuracy_LBP <- mean(LR.test.result_LBP == test_LBP[,1])
LR.test.accuracy_LBP
```


























