---
title: "HOG_with_models"
author: "Shan He"
date: "March 20, 2018"
output: html_document
---

```{r}
packages.used=c("caret","gbm", "e1071", "DMwR", "nnet", "randomForest","OpenImageR","DT", "caTools", "EBImage", "mxnet", "pbapply", "ggthemes")
# check packages that need to be installed.
packages.needed=setdiff(packages.used,
intersect(installed.packages()[,1],
packages.used))
# install additional packages
if(length(packages.needed)>0){
install.packages(packages.needed, dependencies = TRUE)
}

library(caret)
library(gbm)
library(e1071)
library(DMwR)
library(randomForest)
library(nnet)
library(OpenImageR)
library(DT)
library(caTools)
#library(EBImage)
#library(mxnet)
library(pbapply)
library(ggthemes)

source("../lib/train.R")
source("../lib/test.R")
source("../lib/data_split.R")
```


### 1. Retrieve and split the training and test data from the dataset.

```{r}
datasplit_hog <- data_split("hog_extraction")

train_hog <- datasplit_hog$df_train

test_hog <- datasplit_hog$df_test
```


### 2. Classifying with various methods 

#### 2.1.1 GBM training

```{r}
GBM_hog <- train_gbm(train_hog)
save(GBM_hog,file="../output/GBM_hog.RData")
```


#### 2.1.2 GBM testing 

```{r}
load("../output/GBM_hog.RData")
GBM_hog.time <- GBM_hog$time
GBM_hog.time

GBM.test.result_hog <- test_gbm(GBM_hog, test_hog)
GBM.test.accuracy_hog <- mean(GBM.test.result_hog == test_hog[,1])
GBM.test.accuracy_hog
```


#### 2.2.1 SVM training

```{r}
SVM_hog <- train_svm(train_hog)
save(SVM_hog,file="../output/SVM_hog.RData")
```


#### 2.2.2 SVM testing

```{r}
load("../output/SVM_hog.RData")
SVM_hog.time <- SVM_hog$time
SVM_hog.time

SVM.test.result_hog <- test(SVM_hog, test_hog)
SVM.test.accuracy_hog <- mean(SVM.test.result_hog == test_hog[,1])
SVM.test.accuracy_hog
```


#### 2.3.1 Random Forest training

```{r}
RF_hog <- train_rf(train_hog)
save(RF_hog,file="../output/RF_hog.RData")
```


#### 2.3.2 Random Forest testing

```{r}
load("../output/RF_hog.RData")
RF_hog.time <- RF_hog$time
RF_hog.time

RF.test.result_hog <- test(RF_hog, test_hog)
RF.test.accuracy_hog <- mean(RF.test.result_hog == test_hog[,1])
RF.test.accuracy_hog
```


#### 2.4.1 Logistic Regression training

```{r}
LR_hog <- train_lr(train_hog)
save(LR_hog,file="../output/LR_hog.RData")
```


#### 2.4.2 Logistic Regression testing

```{r}
load("../output/LR_hog.RData")
LR_hog.time <- LR_hog$time
LR_hog.time

LR.test.result_hog <- test(LR_hog, test_hog)
LR.test.accuracy_hog <- mean(LR.test.result_hog == test_hog[,1])
LR.test.accuracy_hog
```


























