---
title: "XGBoost"
author: "Michael Utomo"
date: "March 27, 2018"
output: html_document
---

Data Preparation
```{r}
library(xgboost)
df <- read.csv('hog_extraction.csv', header=FALSE)
labels <- read.csv('label_train.csv')
df$label <- as.factor(labels$label)
```


Relabel factors for XGBoost specific num_classes requirement
```{r}
levels(df$label)[levels(df$label)=="1"] <- "0"
levels(df$label)[levels(df$label)=="2"] <- "1"
levels(df$label)[levels(df$label)=="3"] <- "2"
```

Split data into features and target
```{r}
df.features <- df[, -which(colnames(df) == 'label')]
df.features$V1 <- NULL
df.target <- df$label
```

Set up grid of hyperparameters to search over
```{r}
xgb.tune <- expand.grid(eta=c(0.3, 0.5, 0.7),
                        gamma=c(0, 0.5, 1),
                        max_depth = c(2, 3, 4, 5, 10))
xgb.tune$accuracy <- numeric(nrow(xgb.tune))
```


Perform cross validation (CV) iteration on each combination of hyperparameters. Each iteration performs 5-fold CV with 50 rounds of training XGBoost. 
```{r}
set.seed(032718)
for(i in 1:nrow(xgb.tune)){
        t1 = Sys.time()
        print(paste('Starting iteration', i, 'of', nrow(xgb.tune), ':'))
        
        param_list <- list(max_depth=xgb.tune$max_depth[i], 
                           eta=xgb.tune$eta[i], 
                           gamma = xgb.tune$gamma[i], 
                           silent=1, 
                           nthread=2, 
                           objective='multi:softmax')
        
        model <- xgb.cv(data = as.matrix(df.features), 
                        nrounds = 50, 
                        nfold = 5,
                        metrics = list("merror"),
                        label = df.target,
                        params = param_list,
                        num_class = 4)
        
        # Takes mean of 10 training rounds with highest classification rate
        xgb.tune$accuracy[i] <- 1-(mean(sort(model$evaluation_log$test_merror_mean)[1:10])) 
        t2 = Sys.time()
        print(paste('Iteration', i, 'took :', (t2-t1), 'seconds'))
}
```

Find best hyperparameters
```{r}
best.params <- xgb.tune[which.max(xgb.tune$accuracy),]
best.params
```