
# This R file shows how we used the HOG image extraction
install.packages("OpenImageR")
library("OpenImageR")

values <- NULL

path1 <- "C:/StudyLife/Columbia/STAT 5243/local project 3/train/train/images/"

for (i in 1:3000){
  
  length1 <- nchar(as.character(i))
  
  directory <- paste0(path1,paste(rep(0,4 - length1),collapse=""),i,".jpg")
  
  # Retrieve the all the images
  images <- readImage(directory)
  
  # Use HOG function to extract the info of all images
  extractedvalues <- HOG(images)
  
  values <- rbind(values,extractedvalues)
  
}

# Save the info of each image into the hog_extraction file
write.csv(values, file = "hog_extraction.csv")

# After saving the data it is possible that the first row and first column are the header and name automatically generated by the function.
# If it happens, we can just manually delete the first row in the csv file.