---
title: "Neural"
author: "Michael Utomo"
date: "March 19, 2018"
output: html_document
---


```{r}
library(neuralnet)
library(nnet)

df <- read.csv('hog_extraction.csv', header=FALSE)
labels <- read.csv('./train/label_train.csv')
df$label <- as.factor(labels$label) #add a column called label to df
```

Scale Data
```{r}
scl <- function(x){(x-min(x))/(max(x)-min(x))}
target.i <- which(colnames(df)=='label')
df[,-target.i] <- data.frame(lapply(df[,-target.i], scl))
```

Dummy code Outcome Variable
Create 3 variables that pertains the labels are that being predicted
```{r}
df$l1 <- ifelse(df$label=="1", 1,0)
df$l2 <- ifelse(df$label=="2", 1,0)
df$l3 <- ifelse(df$label=="3", 1,0)
df$label <- NULL
```

Split into training and test 
```{r}
set.seed(032518)
test.i <- sample(1:nrow(df), .3*nrow(df), replace=FALSE)
test.data <- df[test.i,]
train.data <- df[-test.i,]
test.target <- labels[test.i, 'label']
```

Set up formula
```{r}
n <- names(train.data)
f <- as.formula(paste("l1 + l2 + l3 ~",paste(n[!n %in% c("l1","l2","l3")], collapse="+")))
```
Problem:Curse of Dimensionality

Gridsearch
Allows to train on all combinations of tuning parameters
```{r}
nn.tune <- expand.grid(hidden=c(1,2,3),
                       act.fct="logistic")
nn.tune$accuracy <- numeric(nrow(nn.tune))

for(i in 1:nrow(nn.tune)){

t1 = Sys.time()
nn <- neuralnet(f,
                data=train.data,
                hidden=nn.tune$hidden[i],
                act.fct=nn.tune$act.fct[i],
                linear.output=FALSE,
                lifesign="minimal",
                stepmax=1e+06)
pr.nn <- compute(nn, test.data[1:(ncol(test.data)-3)])
nn.pred <- apply(pr.nn$net.result, 1, which.max)
nn.tune$accuracy[i] <- mean(nn.pred==test.target)
t2 <- Sys.time()

print(paste('On iteration', i, 'We trained a neural network with hidden parameter = ', nn.tune$hidden[i], "and a ", nn.tune$act.fct, 'activation function.', 'It took:'))
print(t2-t1)
}
```

```{r}
best.params <- nn.tune[which.max(nn.tune$accuracy), c('hidden', 'act.fct')]

# Re-train our best model
t1 = Sys.time()

nn <- neuralnet(f,
                data=train.data,
                hidden=best.params$hidden,
                act.fct=best.params$act.fct,
                linear.output=FALSE,
                lifesign="minimal")
pr.nn <- compute(nn, test.data[1:2000])
nn.pred <- apply(pr.nn$net.result, 1, which.max)
best.accuracy <- mean(nn.pred==test.target)
print(t2-t1)

print(paste('Our best accuracy was', best.accuracy))

```




